language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install -r requirements.txt"
script:
  - nosetests
  - pyflakes rgkit test
  - ./build-docs.sh
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#robotgame"
    use_notice: true
    on_success: change
    on_failure: always
